"""empty message

Revision ID: a0a3d8301838
Revises: d6123e49e55a
Create Date: 2020-05-24 18:20:10.158032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a3d8301838'
down_revision = 'd6123e49e55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('done', sa.Column('department', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('done', 'department')
    # ### end Alembic commands ###
