"""empty message

Revision ID: d6123e49e55a
Revises: 7f7fec0cab23
Create Date: 2020-05-24 07:31:06.799286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6123e49e55a'
down_revision = '7f7fec0cab23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('done',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start', sa.Time(), nullable=True),
    sa.Column('end', sa.Time(), nullable=True),
    sa.Column('fsp', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('numPeople', sa.Integer(), nullable=True),
    sa.Column('student', sa.String(length=60), nullable=True),
    sa.Column('sid', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('done')
    # ### end Alembic commands ###
